title: "[Receitas IA](https://agents4good.github.io/ReceitasIA/)"
description: Um livro de receitas para modelos de linguagem Open-Source.
url: https://agents4good.github.io/ReceitasIA/
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
